// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmnJsBAoBGoyVvb4Ey2qy6IJT5BJ52UM',
    appId: '1:668603629867:web:a6390f44f50a860c69c56e',
    messagingSenderId: '668603629867',
    projectId: 'quickcart-app-402d8',
    authDomain: 'quickcart-app-402d8.firebaseapp.com',
    storageBucket: 'quickcart-app-402d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMTMYFX4wR3X3xn6h8dlOdzDPzDwaY1E',
    appId: '1:668603629867:android:a0b7c46c3109279d69c56e',
    messagingSenderId: '668603629867',
    projectId: 'quickcart-app-402d8',
    storageBucket: 'quickcart-app-402d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAoKfR_ZDWolTUIf7eSCVieM_cP3uTTeo',
    appId: '1:668603629867:ios:04204ea6f496c70269c56e',
    messagingSenderId: '668603629867',
    projectId: 'quickcart-app-402d8',
    storageBucket: 'quickcart-app-402d8.firebasestorage.app',
    iosBundleId: 'com.example.blinkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAoKfR_ZDWolTUIf7eSCVieM_cP3uTTeo',
    appId: '1:668603629867:ios:04204ea6f496c70269c56e',
    messagingSenderId: '668603629867',
    projectId: 'quickcart-app-402d8',
    storageBucket: 'quickcart-app-402d8.firebasestorage.app',
    iosBundleId: 'com.example.blinkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUmnJsBAoBGoyVvb4Ey2qy6IJT5BJ52UM',
    appId: '1:668603629867:web:ec5ba10f74d50cc369c56e',
    messagingSenderId: '668603629867',
    projectId: 'quickcart-app-402d8',
    authDomain: 'quickcart-app-402d8.firebaseapp.com',
    storageBucket: 'quickcart-app-402d8.firebasestorage.app',
  );
}
